In [1]:
import csv
import numpy as np
import scipy as sp

Put here the path to the 'EMPORIOSIRENUSE_20173012' folder

In [4]:
path_to_dataset = '../'

Import concepts file (as a dictionary with post id as a key and words as values)

In [7]:
concepts = {}
concepts_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/emporiosirenuse/emporiosirenuse_concepts.csv'
with open(concepts_file, 'r') as file:
    filereader = csv.reader(file, delimiter=";")
    for row in filereader:
        concepts[row[0]] = [x.split('\t')[0] for x in row[2:]]
del concepts['id_post']
print(concepts)

{'1626715614041340120': ['city', 'tourism', 'travel', 'urban', 'architecture', 'street', 'building', 'sky', 'house', 'sight', 'water', 'town', 'tourist', 'landscape', 'outdoors', 'old', 'vacation', 'people', 'cityscape', 'sea', ''], '1624081541577781641': ['blur', 'flower', 'portrait', 'christmas', 'people', 'girl', 'nature', 'outdoors', 'focus', 'tree', 'adult', 'wedding', 'grass', 'park', 'woman', 'summer', 'one', 'winter', 'celebration', 'garden', ''], '1622755917101740863': ['travel', 'tourism', 'architecture', 'town', 'water', 'city', 'seashore', 'sea', 'resort', 'vacation', 'outdoors', 'building', 'tourist', 'people', 'house', 'restaurant', 'landscape', 'hotel', 'beach', 'no person', ''], '1619544083599159430': ['woman', 'adult', 'portrait', 'fashion', 'people', 'model', 'girl', 'competition', 'business', 'wear', 'sunglasses', 'fashionable', 'summer', 'one', 'dress', 'indoors', 'auto racing', 'stock', 'race', 'footwear', ''], '1618082415471902658': ['desktop', 'rock', 'texture', 

In [38]:
posts = []
likes = []
posts_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/emporiosirenuse/emporiosirenuse_posts.csv'
with open(posts_file, 'r') as file:
    filereader = csv.reader(file, delimiter=",")
    next(filereader)
    for row in filereader:
        posts.append(row[0])
        likes.append(int(row[12]))
posts = np.array(posts)
likes = np.array(likes)

In [43]:
top30 = np.flip(posts[np.argsort(likes)[-30:]], 0)

In [59]:
unique, counts = np.unique(np.ravel([concepts[i] for i in top30]), return_counts = True)
unique = unique[1:]
counts = counts[1:]
print(unique)
print(counts)

['adult' 'ancient' 'antique' 'architecture' 'art' 'bar' 'bay' 'beach'
 'beautiful' 'bedroom' 'bikini' 'boat' 'boutique' 'branch' 'buddha'
 'building' 'chair' 'chandelier' 'church' 'city' 'cityscape' 'coffee table'
 'commerce' 'concert' 'culture' 'dawn' 'daylight' 'decoration' 'design'
 'desktop' 'dining' 'dining room' 'door' 'dress' 'dusk' 'easy chair'
 'enjoyment' 'evening' 'exhibition' 'fair weather' 'family' 'fashion'
 'fashionable' 'festival' 'fjord' 'flower' 'fun' 'furniture' 'geisha'
 'girl' 'glamour' 'glass items' 'group' 'group together' 'hanger' 'hanging'
 'happiness' 'harbor' 'hill' 'home' 'hotel' 'house' 'idyllic' 'indoors'
 'inside' 'interior design' 'island' 'kimono' 'lake' 'lamp' 'landmark'
 'landscape' 'leisure' 'lifestyle' 'light' 'lighthouse' 'luxury' 'mall'
 'man' 'mannequin' 'many' 'market' 'merchandise' 'military' 'mirror'
 'model' 'monochrome' 'mountain' 'music' 'musician' 'nature' 'nightclub'
 'no person' 'ocean' 'old' 'one' 'option' 'ornate' 'outdoors' 'people'
 

Here are the 20 most frequent concepts in the top 30 liked posts

In [67]:
print(np.flip(unique[np.argsort(counts)[-30:]], 0))

['travel' 'water' 'sea' 'outdoors' 'no person' 'seashore' 'architecture'
 'vacation' 'landscape' 'tourism' 'sky' 'beach' 'house' 'summer' 'city'
 'building' 'town' 'people' 'ocean' 'island' 'sight' 'nature' 'bay' 'adult'
 'scenic' 'sunset' 'daylight' 'cityscape' 'woman' 'dawn']


In [66]:
print(np.flip(counts[np.argsort(counts)[-30:]], 0))

[26 23 21 20 20 18 17 16 15 15 14 14 13 12 12 11 11 11 10  9  9  7  6  6  5
  5  5  5  5  4]


# miguelina gambaccini - mostly tags - 82358 followers

TAGS

In [160]:
miguelina_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/miguelinagambaccini/miguelinagambaccini_tags.csv'
miguelina = np.genfromtxt(miguelina_file, delimiter=',', dtype=str)

remove headers

In [161]:
miguelina = miguelina[1:]

In [162]:
unique, counts = np.unique(miguelina[:,0], return_counts=True)

In [163]:
np.flip(counts[np.argsort(counts)[-10:]],  0)

array([167, 126, 106,  42,  36,  24,  20,  18,  16,  11], dtype=int64)

In [164]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(tags)

['miguelinamoment' 'roundtheworldinmiguelina' 'globalbabes' 'miguelina'
 'junglelife' 'tulum' 'miguelinatulum' 'SS17' 'globalbabe' 'ss17']


In [165]:
with open('miguelinagambaccini_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [18]:
miguelina_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/miguelinagambaccini/miguelinagambaccini_mentions.csv'
miguelina = np.genfromtxt(miguelina_file, delimiter=',', dtype=str)
miguelina = miguelina[1:]
unique, counts = np.unique(miguelina[:,0], return_counts=True)

In [167]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[18 14  8  8  7  6  6  5  5  5]


In [168]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(mentions)

['charlottehayesjones' 'miguelinagambaccini' 'netaporter' 'ritzparis'
 'mathildefrachon' 'our' 'natlamblin' 'veuveclicquot' 'emiliebrouss'
 'annesserra']


In [169]:
with open('miguelinagambaccini_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

# muzungu sisters - mostly mentions - 66950 followers

MENTIONS

In [170]:
muzungu_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/muzungusisters/muzungusisters_mentions.csv'
muzungu = np.genfromtxt(muzungu_file, delimiter=',', dtype=str)
muzungu = muzungu[1:]
unique, counts = np.unique(muzungu[:,0], return_counts=True)

In [171]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[8 4 3 3 3 3 2 2 2 1]


In [172]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['lacoquetakids' 'farmacyuk' 'magneticmidnight' 'rachelljonesartist'
 'sabinegetty' 'simonjevans' 'sophia' 'roxysowlaty' 'disfunkshionmag'
 'carlaypage']


In [173]:
with open('muzungusisters_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

TAGS

In [174]:
muzungu_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/muzungusisters/muzungusisters_tags.csv'
muzungu = np.genfromtxt(muzungu_file, delimiter=',', dtype=str)
muzungu = muzungu[1:]
unique, counts = np.unique(muzungu[:,0], return_counts=True)

In [175]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[45 24 15  3  2  2  2  2  1  1]


In [176]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['muzungusisters' 'MuzunguSisters' 'lacoquetaxmuzungusisters'
 'magneticmidnightxmuzungusisters' 'handembroidered' 'handmade'
 'MagneticMidnightxMuzunguSisters' 'artisanal' 'yearoftherooster' 'TBT']


In [177]:
with open('muzungusisters_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

# zeus + dione - mostly tags - 27673 followers

TAGS

In [178]:
zeusndione_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/zeusndione/zeusndione_tags.csv'
zeusndione = np.genfromtxt(zeusndione_file, delimiter=',', dtype=str)
zeusndione = zeusndione[1:]
unique, counts = np.unique(zeusndione[:,0], return_counts=True)

In [179]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[201  49  40  32  32  29  26  19  19  15]


In [180]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['zeusndione' 'inspiration' 'handmade' 'art' 'greece' 'madeingreece'
 'summer' 'ootd' 'musthave' 'colours']


In [181]:
with open('zeusndione_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [182]:
zeusndione_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/zeusndione/zeusndione_mentions.csv'
zeusndione = np.genfromtxt(zeusndione_file, delimiter=',', dtype=str)
zeusndione = zeusndione[1:]
unique, counts = np.unique(zeusndione[:,0], return_counts=True)

In [183]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[7 7 6 5 5 5 4 4 4 4]


In [184]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['olympiakrasagaki' 'themodist' 'lydia' 'matchesfashion' 'netaporter'
 'marevagr' 'mimik' 'thebenakimuseum' 'theeyetravels' 'farfetch']


In [185]:
with open('zeusndione_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

# Dodo Bar Or - mostly mentions and picture tags

MENTIONS

In [186]:
dodobaror_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/dodobaror/dodobaror_mentions.csv'
dodobaror = np.genfromtxt(dodobaror_file, delimiter=',', dtype=str)
dodobaror = dodobaror[1:]
unique, counts = np.unique(dodobaror[:,0], return_counts=True)

In [187]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[32 29 29 29 29 28 27 19 17  9]


In [188]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['netaporter' 'shopbop' 'matchesfashion' 'modaoperandi' 'mytheresa'
 'revolve' 'fwrd' 'avenue32' 'intermixonline' 'adakokosar']


In [189]:
with open('dodobaror_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

PIC TAGS

In [190]:
dodobaror_file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/dodobaror/dodobaror_picture_tags.csv'
dodobaror = np.genfromtxt(dodobaror_file, delimiter=',', dtype=str)
dodobaror = dodobaror[1:]
unique, counts = np.unique(dodobaror[:,2], return_counts=True)

In [191]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[74 28 25 25 24 24 24 23 23 10]


In [192]:
top_pic_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_pic_tags)

['dodobaror' 'netaporter' 'matchesfashion' 'avenue32' 'mytheresa.com'
 'modaoperandi' 'shopbop' 'revolve' 'fwrd' 'intermixonline']


In [193]:
with open('dodobaror_top_pic_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_pic_tags[i]) + ', ' + str(top_counts[i]) + '\n')

# Lisa Marie Fernandez - mostly tags and mentions - 83421 followers

TAGS

In [194]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/lisamariefernandez/lisamariefernandez_tags.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [195]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[178 115  36  27  27  23  21  13   8   8]


In [196]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['lisamariefernandez' 'LMFgirlsONholiday' 'topanga' 'spring2017collection'
 'malibu' 'california' 'californication' 'resort2017collection'
 'joseignacio' 'bikini']


In [197]:
with open('lisamariefernandez_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [198]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/lisamariefernandez/lisamariefernandez_mentions.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [199]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[16  6  6  6  4  4  3  3  3  3]


In [200]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['matchesfashion' 'themostfamousartist' 'netaporter' 'imaanhammam'
 'ericapelosini' 'voguemagazine' 'haileybaldwin' 'somethingnavy' 'hoskelsa'
 'vitakin']


In [201]:
with open('lisamariefernandez_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

# Loup charmant - mostly mentions and tags - 20446 followers

MENTIONS

In [9]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/loupcharmant/loupcharmant_mentions.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [10]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[30 18 18  7  7  5  5  5  5  4]


In [11]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['loupcharmant' 'willysomma' 'matchesfashion' 'theperfecthideaway'
 'stylesavageuk' 'popupcollectivesh' 'arunaseth' 'clarissabronfman'
 'worldarmarium' 'jenniferfisherjewelry']


In [12]:
with open('loupcharmant_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

TAGS

In [13]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/loupcharmant/loupcharmant_tags.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [14]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[144  57   7   5   4   4   4   4   3   3]


In [15]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['loupcharmant' 'vibecharmant' 'LoupCharmant' 'marfa' 'wanderlust' 'yellow'
 'southampton' 'beachlife' 'indiansummer' 'breezy']


In [16]:
with open('loupcharmant_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

# Athena Procopiou - mostly tags and mentions - 26593 followers

TAGS

In [210]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/athenaprocopiou/athenaprocopiou_tags.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [211]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[127  86  82  74  66  65  53  51  49  43]


In [212]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['athenaprocopiou' 'summer' 'love' 'bohochic' 'dress' 'summerstyle'
 'prints' 'boho' 'fashion' 'resortwear']


In [213]:
with open('athenaprocopiou_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [214]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/athenaprocopiou/athenaprocopiou_mentions.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [215]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[11  8  8  8  8  5  4  3  2  2]


In [216]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['jamesbrooks' 'spirossavvinos' 'sophia' 'stamatis' 'matchesfashion'
 'amberfillerup' 'hereccomes' 'sorayabakhtiar' 'carajourdan' 'juliahengel']


In [217]:
with open('athenaprocopiou_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

# Emporio Le Sirenuse - mostly tags and mentions - 3119 followers

TAGS

In [218]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/emporiosirenuse/emporiosirenuse_tags.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [219]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[96 39 31 25 25 19 16 15 15 15]


In [220]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['LeSirenusePositanoCollection' 'ig' 'Positano' 'AmalfiCoast' 'SS17'
 'summertime' 'ilovepositano' 'womenswear' 'luxurytravel' 'beachwear']


In [221]:
with open('emporiosirenuse_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [222]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/emporiosirenuse/emporiosirenuse_mentions.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [223]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[37 36  5  5  3  3  3  2  2  2]


In [224]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['guidotaroniphotographer' 'robertosalomonephotojournalist'
 'nusaindahsurfboards' 'francosbar' 'bitterendproductions' 'mjgiuls'
 'louisnicolasdarbon' 'rr' 'sarahamandabray' 'speronella']


In [225]:
with open('emporiosirenuse_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

# Heidi Klein Swimwear - mostly tags and mentions - 27425 followers

TAGS

In [226]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/heidikleinswim/heidikleinswim_tags.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [227]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[257 215 200 158 147  97  94  87  84  78]


In [228]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['HeidiKlein' 'love' 'style' 'swimwear' 'travel' 'potd' 'summer' 'shopnow'
 'destination' 'fblogger']


In [229]:
with open('heidikleinswim_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [230]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/heidikleinswim/heidikleinswim_mentions.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [231]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[12 10  7  7  6  6  5  5  4  4]


In [232]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['lornaluxe' 'hedvigso' 'bonnierakhit' 'sophieandersonbags' 'kavitacola'
 'sincerelyjules' 'gypsylovinlight' 'tessward' 'theglowedit' 'niomismart']


In [233]:
with open('heidikleinswim_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')

# Daft Collection - mostly tags and mentions - 3781 followers

TAGS

In [234]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/daftcollectionofficial/daftcollectionofficial_tags.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [235]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[54 31 20 16 12 11 11 10  8  8]


In [236]:
top_tags = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_tags)

['holiday' 'summer' 'summertime' 'notjustforthebeach' 'chic' 'beachlife'
 'weekend' 'beach' 'beachchic' 'resort']


In [237]:
with open('daftcollectionofficial_top_tags.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_tags[i]) + ', ' + str(top_counts[i]) + '\n')

MENTIONS

In [4]:
file = path_to_dataset + 'EMPORIOSIRENUSE_20173012/daftcollectionofficial/daftcollectionofficial_mentions.csv'
data = np.genfromtxt(file, delimiter=',', dtype=str)[1:]
unique, counts = np.unique(data[:,0], return_counts=True)

In [5]:
top_counts = np.flip(counts[np.argsort(counts)[-10:]],  0)
print(top_counts)

[17  8  5  5  5  4  3  3  3  3]


In [6]:
top_mentions = np.flip(unique[np.argsort(counts)[-10:]],  0)
print(top_mentions)

['matchesfashion' 'edenbeing' 'milaura' 'winwoodfashion'
 'adamheathboutique' 'alducadaosta' 'paciugomantova' 'victoireofficiel'
 'josephfashion' 'serenellausa']


In [8]:
with open('daftcollectionofficial_top_mentions.csv', 'w') as file:
    for i in range(10):
        file.write(str(top_mentions[i]) + ', ' + str(top_counts[i]) + '\n')